name: manual trigger tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test on'
        required: true
      pytorch_nightly:
        description: 'Whether to use PyTorch nightly'
        required: false
        default: false

jobs:
  run_tests_on_branch:
    runs-on: ubuntu-latest
    env:
      PEFT_DEBUG_WITH_TORCH_COMPILE: 123
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "setup.py"
      - name: Install dependencies
        run: |
          git status
          echo $PEFT_DEBUG_WITH_TORCH_COMPILE
          if [ "${{ github.event.inputs.pytorch_nightly }}" = "true" ]; then
            echo "pretending to isntall PyTorch nightly"
          fi
          pip --version
          pip install .
          pip install pytest
          pip list
      - name: Run the tests
        run: |
          pytest mops/tests/
